### ISSUE TITLE
migrate frontend to tsx, refactoring, and resolve tslint issues

### ISSUE THREAD

**Issue by g00gol** [hubba-lubba/hubba#26]
- [ ] migrate frontend to tsx
- [ ] resolve tslint issues
- [ ] refactoring

**Comment by g00gol** [comment]
@iscii assign issue to me pls

**Comment by g00gol** [comment]
opened issue in submodule gh: https://github.com/jingsnx/hubba-prototype/pull/2

**Comment by g00gol** [comment]
blocked by #28

**Comment by iscii** [comment]
> blocked by #28

how blocked?

**Comment by g00gol** [comment]
> > blocked by #28
> 
> how blocked?

im working to split up this issue into smaller parts. first, im making a tslint issue
